const MY_GAMES = [
    {
        id: "tfg",
        title: "Proyecto Final de Grado",
        title_en: "Final Degree Project",
        description: "Juego en desarrollo. Metroidvania basado en 'Mistborn' de Brandon Sanderson y Blasphemous II.",
        description_en: "Game in development. Metroidvania based on Brandon Sanderson's 'Mistborn' and Blasphemous II.",
        extendedDescription: "Este es el trabajo de final de grado en el que estoy poniendo en práctica todos los conocimientos adquiridos durante los últimos años. El proyecto busca crear un metroidvania único, centrado en una atmósfera cuidada, unas mecánicas innovadoras basadas en el sistema alomántico de 'Mistborn' y un estilo artístico que fusione la crudeza de Blasphemous II con la elegancia de la ambientación creada por Sanderson. Actualmente en estado de conceptualización.",
        extendedDescription_en: "This is the final degree project where I am putting into practice all the knowledge acquired over the last few years. The project seeks to create a unique metroidvania, focused on a carefully crafted atmosphere, innovative mechanics based on the allomantic system of 'Mistborn' and an art style that merges the rawness of Blasphemous II with the elegance of Sanderson's setting. Currently in the conceptualization stage.",
        image: "assets/images/Proximamente_TFG.png",
        link: "#",
        isFeatured: true,
        isInDevelopment: true,
        tags: [{ name: "Unity", class: "t-unity" }, { name: "2D", class: "t-2d" }, { name: "Metroidvania", class: "t-metroidvania" }],
        duration: "-",
        duration_en: "-",
        status: "En desarrollo",
        status_en: "In development",
        type: "TFG"
    },
    {
        id: "twrm",
        title: "They Wont Retain Me",
        title_en: "They Wont Retain Me",
        description: "El infierno no quiere que escapes. Sobrevive a hordas de pecadores y demonios mientras construyes builds cada vez más poderosas.",
        description_en: "Hell doesn't want you to escape. Survive hordes of sinners and demons while building increasingly powerful builds.",
        image: "assets/images/TWRM_Portada.png",
        link: "https://abelirre.itch.io/they-wont-retain-me",
        isFeatured: false,
        isInDevelopment: false,
        tags: [{ name: "Unreal Engine", class: "t-unreal" }, { name: "3D", class: "t-3d" }, { name: "Acción", class: "t-accion" }, { name: "Survivor-like", class: "t-platformer" }],
        duration: "3 meses",
        duration_en: "3 months",
        status: "Acabado",
        status_en: "Finished",
        type: "Uni Project"
    },
    {
        id: "bloodrunner",
        title: "Blood Runner",
        title_en: "Blood Runner",
        description: "Un platformer 2D pixel art con enemigos y mucho frenetismo. Proyecto universitario.",
        description_en: "A fast-paced 2D pixel art platformer with enemies. University project.",
        image: "assets/images/BloodRunner_Portada.png",
        link: "https://abelirre.itch.io/bloodrunner",
        isFeatured: false,
        isInDevelopment: false,
        tags: [{ name: "Godot", class: "t-godot" }, { name: "2D", class: "t-2d" }, { name: "Pixel Art", class: "t-pixel" }, { name: "Plataformas", class: "t-platformer" }],
        duration: "3 meses",
        duration_en: "3 months",
        status: "Acabado",
        status_en: "Finished",
        type: "Uni Project"
    },
    {
        id: "desinformator",
        title: "Desinformator",
        title_en: "Desinformator",
        description: "Juego 3D en primera persona en el que el jugador está en un sótano intentando desinformar al mundo entero.",
        description_en: "3D first-person game where the player is in a basement trying to misinform the whole world.",
        image: "assets/images/Desinformator_Portada.png",
        link: "https://abelirre.itch.io/desinformator",
        isFeatured: false,
        isInDevelopment: false,
        tags: [{ name: "Godot", class: "t-godot" }, { name: "3D", class: "t-3d" }, { name: "Estrategia", class: "t-estrategia" }],
        duration: "1 mes",
        duration_en: "1 month",
        status: "Acabado",
        status_en: "Finished",
        type: "JAM"
    },
    {
        id: "warehouse",
        title: "The Warehouse",
        title_en: "The Warehouse",
        description: "Adéntrate en un almacén aislado en las montañas y descubre los secretos más oscuros que allí se guardan.",
        description_en: "Venture into an isolated warehouse in the mountains and discover the darkest secrets kept there.",
        image: "assets/images/TheWarehouse_Portada.png",
        link: "https://abelirre.itch.io/the-warehouse",
        isFeatured: false,
        isInDevelopment: false,
        tags: [{ name: "Unity", class: "t-unity" }, { name: "3D", class: "t-3d" }, { name: "Aventura", class: "t-aventura" }, { name: "Terror", class: "t-terror" }],
        duration: "2 meses",
        duration_en: "2 months",
        status: "Acabado",
        status_en: "Finished",
        type: "Uni Project"
    },
];
